# Data Preprocessing
[PCBA](https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/pcba.zip) -- Selected from PubChem BioAssay, consisting of measured biological activities of small molecules generated by high-throughput screening.

[MUV](https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/muv.zip) -- Subset of PubChem BioAssay by applying a refined nearest neighbor analysis, designed for validation of virtual screening techniques.

[HIV](https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/hiv.zip) -- Experimentally measured abilities to inhibit HIV replication.

[BACE](https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/bace.zip) -- Quantitative (IC50) and qualitative (binary label) binding results for a set of inhibitors of human Î²-secretase 1(BACE-1).

[CHEMBL](ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_26.sdf.gz)  -- ext.

-------------------------------------
Download & Extract PCBA File ( CSV )
--------------------------------------

In [0]:
import requests

In [0]:
url = 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/pcba.zip'
r = requests.get(url, allow_redirects=True)

In [0]:
open('PCBA', 'wb').write(r.content)

15450075

In [0]:
from zipfile import ZipFile

In [0]:
cd /content/drive/My\ Drive

/content/drive/My Drive

In [0]:
with ZipFile('PCBA.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

--------------------------------------
Download & Extract MUV File ( CSV )
---------------------------------------

In [0]:
url = 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/muv.zip'
r = requests.get(url, allow_redirects=True)

In [0]:
open('MVU', 'wb').write(r.content)

1756297

In [0]:
with ZipFile('MVU.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

--------------------------------------
Download & Extract HIV File ( CSV )
---------------------------------------

In [0]:
url = 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/hiv.zip'
r = requests.get(url, allow_redirects=True)

In [0]:
open('HIV.zip', 'wb').write(r.content)

426931

In [0]:
with ZipFile('HIV.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

--------------------------------------
Download & Extract BACE File ( CSV )
---------------------------------------

In [0]:
url = 'https://s3-us-west-1.amazonaws.com/deepchem.io/datasets/molnet_publish/bace.zip'
r = requests.get(url, allow_redirects=True)

In [0]:
open('BACE.zip', 'wb').write(r.content)

1268761

In [0]:
with ZipFile('BACE.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall()

-------------------
 Integrate CSV Files
 -------------------

In [0]:
import pandas as pd

In [4]:
cd /content/drive/My\ Drive/Data.csv

/content/drive/My Drive/Data.csv

.
**HIV Data**
.

In [0]:
HIVdata = pd.read_csv("HIV.csv")

In [0]:
HIVdata

                                                  smiles activity  HIV_active
0      CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...       CI           0
1      C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...       CI           0
2                       CC(=O)N1c2ccccc2Sc2c1ccc1ccccc21       CI           0
3        Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1       CI           0
4                                 O=S(=O)(O)CCS(=O)(=O)O       CI           0
...                                                  ...      ...         ...
41122  CCC1CCC2c3c([nH]c4ccc(C)cc34)C3C(=O)N(N(C)C)C(...       CI           0
41123  Cc1ccc2[nH]c3c(c2c1)C1CCC(C(C)(C)C)CC1C1C(=O)N...       CI           0
41124  Cc1ccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)C...       CI           0
41125  Cc1cccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)...       CI           0
41126  CCCCCC=C(c1cc(Cl)c(OC)c(-c2nc(C)no2)c1)c1cc(Cl...       CI           0

[41127 rows x 3 columns]

.
**BACE Data**
.

In [0]:
BACEdata = pd.read_csv("bace.csv")

In [0]:
BACEdata

                                                    mol  ... canvasUID
0     O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...  ...         1
1     Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...  ...         2
2     S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...  ...         3
3     S1(=O)(=O)C[C@@H](Cc2cc(O[C@H](COCC)C(F)(F)F)c...  ...         4
4     S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...  ...         5
...                                                 ...  ...       ...
1508          Clc1cc2nc(n(c2cc1)C(CC(=O)NCC1CCOCC1)CC)N  ...      1543
1509          Clc1cc2nc(n(c2cc1)C(CC(=O)NCc1ncccc1)CC)N  ...      1544
1510             Brc1cc(ccc1)C1CC1C=1N=C(N)N(C)C(=O)C=1  ...      1545
1511       O=C1N(C)C(=NC(=C1)C1CC1c1cc(ccc1)-c1ccccc1)N  ...      1546
1512                Clc1cc2nc(n(c2cc1)CCCC(=O)NCC1CC1)N  ...      1547

[1513 rows x 595 columns]

In [0]:
MUVdata = pd.read_csv("muv.csv")

In [0]:
MUVdata

       MUV-466  ...                                             smiles
0          NaN  ...    Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C
1          0.0  ...                Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1
2          NaN  ...  COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...
3          NaN  ...  O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...
4          0.0  ...                          NC(=O)NC(Cc1ccccc1)C(=O)O
...        ...  ...                                                ...
93082      NaN  ...                           O=C(NCc1ccccc1Cl)C1CCCO1
93083      NaN  ...        COc1cc(NCCCCCN2C(=O)c3ccccc3C2=O)c2ncccc2c1
93084      NaN  ...                 CCN(CC)c1ccc(/C=C2/C(=O)ON=C2C)cc1
93085      NaN  ...   Cc1cc(=O)oc2cc(OCC(=O)c3ccc4c(c3)NC(=O)CO4)ccc12
93086      NaN  ...           COc1ccc([N+](=O)[O-])cc1NC(=O)c1ccc(C)o1

[93087 rows x 19 columns]

In [0]:
PCBAdata = pd.read_csv("pcba.csv")

In [0]:
PCBAdata

        PCBA-1030  ...                                             smiles
0             0.0  ...               CC(=O)N1CCC2(CC1)NC(=O)N(c1ccccc1)N2
1             0.0  ...                         N#Cc1nnn(-c2ccc(Cl)cc2)c1N
2             NaN  ...      COC(=O)c1ccc(NC(=O)c2ccccc2CC[N+](=O)[O-])cc1
3             NaN  ...            CCC1NC(=O)c2cccnc2-n2c1nc1ccc(F)cc1c2=O
4             NaN  ...  CC1=CC(=O)/C(=C2/C=C(C(=O)Nc3ccc(S(=O)(=O)Nc4o...
...           ...  ...                                                ...
437924        NaN  ...                      CC1CCC2C(C1)OS(=O)(=O)NC2(C)C
437925        NaN  ...                             O=Cc1cc(CCC(=O)O)ccc1O
437926        0.0  ...        O=c1nc(CN2CCN(c3ccc(F)cc3)CC2)[nH]c2ccccc12
437927        NaN  ...             Cc1ccc(C(C)C)c(OCC(O)CN(C)Cc2ccccc2)c1
437928        NaN  ...   CCN(CC(=O)Nc1ccc(C)c(S(=O)(=O)N(C)C)c1)Cc1ccccc1

[437929 rows x 130 columns]

In [0]:
HIVdata['smiles']

0        CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...
1        C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...
2                         CC(=O)N1c2ccccc2Sc2c1ccc1ccccc21
3          Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1
4                                   O=S(=O)(O)CCS(=O)(=O)O
                               ...
41122    CCC1CCC2c3c([nH]c4ccc(C)cc34)C3C(=O)N(N(C)C)C(...
41123    Cc1ccc2[nH]c3c(c2c1)C1CCC(C(C)(C)C)CC1C1C(=O)N...
41124    Cc1ccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)C...
41125    Cc1cccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)...
41126    CCCCCC=C(c1cc(Cl)c(OC)c(-c2nc(C)no2)c1)c1cc(Cl...
Name: smiles, Length: 41127, dtype: object

In [0]:
BACEdata['mol']

0       O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...
1       Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...
2       S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...
3       S1(=O)(=O)C[C@@H](Cc2cc(O[C@H](COCC)C(F)(F)F)c...
4       S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...
                              ...
1508            Clc1cc2nc(n(c2cc1)C(CC(=O)NCC1CCOCC1)CC)N
1509            Clc1cc2nc(n(c2cc1)C(CC(=O)NCc1ncccc1)CC)N
1510               Brc1cc(ccc1)C1CC1C=1N=C(N)N(C)C(=O)C=1
1511         O=C1N(C)C(=NC(=C1)C1CC1c1cc(ccc1)-c1ccccc1)N
1512                  Clc1cc2nc(n(c2cc1)CCCC(=O)NCC1CC1)N
Name: mol, Length: 1513, dtype: object

In [0]:
MUVdata['smiles']

0          Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C
1                      Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1
2        COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...
3        O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...
4                                NC(=O)NC(Cc1ccccc1)C(=O)O
                               ...
93082                             O=C(NCc1ccccc1Cl)C1CCCO1
93083          COc1cc(NCCCCCN2C(=O)c3ccccc3C2=O)c2ncccc2c1
93084                   CCN(CC)c1ccc(/C=C2/C(=O)ON=C2C)cc1
93085     Cc1cc(=O)oc2cc(OCC(=O)c3ccc4c(c3)NC(=O)CO4)ccc12
93086             COc1ccc([N+](=O)[O-])cc1NC(=O)c1ccc(C)o1
Name: smiles, Length: 93087, dtype: object

In [0]:
PCBAdata['smiles']

0                      CC(=O)N1CCC2(CC1)NC(=O)N(c1ccccc1)N2
1                                N#Cc1nnn(-c2ccc(Cl)cc2)c1N
2             COC(=O)c1ccc(NC(=O)c2ccccc2CC[N+](=O)[O-])cc1
3                   CCC1NC(=O)c2cccnc2-n2c1nc1ccc(F)cc1c2=O
4         CC1=CC(=O)/C(=C2/C=C(C(=O)Nc3ccc(S(=O)(=O)Nc4o...
                                ...
437924                        CC1CCC2C(C1)OS(=O)(=O)NC2(C)C
437925                               O=Cc1cc(CCC(=O)O)ccc1O
437926          O=c1nc(CN2CCN(c3ccc(F)cc3)CC2)[nH]c2ccccc12
437927               Cc1ccc(C(C)C)c(OCC(O)CN(C)Cc2ccccc2)c1
437928     CCN(CC(=O)Nc1ccc(C)c(S(=O)(=O)N(C)C)c1)Cc1ccccc1
Name: smiles, Length: 437929, dtype: object

In [0]:
Integratedata = [HIVdata['smiles'], BACEdata['mol'], MUVdata['smiles'], PCBAdata['smiles']]

In [0]:
Integratedata

[0        CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...
 1        C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...
 2                         CC(=O)N1c2ccccc2Sc2c1ccc1ccccc21
 3          Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1
 4                                   O=S(=O)(O)CCS(=O)(=O)O
                                ...
 41122    CCC1CCC2c3c([nH]c4ccc(C)cc34)C3C(=O)N(N(C)C)C(...
 41123    Cc1ccc2[nH]c3c(c2c1)C1CCC(C(C)(C)C)CC1C1C(=O)N...
 41124    Cc1ccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)C...
 41125    Cc1cccc(N2C(=O)C3c4[nH]c5ccccc5c4C4CCC(C(C)(C)...
 41126    CCCCCC=C(c1cc(Cl)c(OC)c(-c2nc(C)no2)c1)c1cc(Cl...
 Name: smiles, Length: 41127, dtype: object,
 0       O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2c...
 1       Fc1cc(cc(F)c1)C[C@H](NC(=O)[C@@H](N1CC[C@](NC(...
 2       S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...
 3       S1(=O)(=O)C[C@@H](Cc2cc(O[C@H](COCC)C(F)(F)F)c...
 4       S1(=O)(=O)N(c2cc(cc3c2n(cc3CC)CC1)C(=O)N[C@H](...
                               ...
 1508            Clc1cc2nc(n(c2cc1)C(CC(=O)NCC1CCOCC1)CC)N
 1509            Clc1cc2nc(n(c2cc1)C(CC(=O)NCc1ncccc1)CC)N
 1510               Brc1cc(ccc1)C1CC1C=1N=C(N)N(C)C(=O)C=1
 1511         O=C1N(C)C(=NC(=C1)C1CC1c1cc(ccc1)-c1ccccc1)N
 1512                  Clc1cc2nc(n(c2cc1)CCCC(=O)NCC1CC1)N
 Name: mol, Length: 1513, dtype: object,
 0          Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C
 1                      Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1
 2        COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...
 3        O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...
 4                                NC(=O)NC(Cc1ccccc1)C(=O)O
                                ...
 93082                             O=C(NCc1ccccc1Cl)C1CCCO1
 93083          COc1cc(NCCCCCN2C(=O)c3ccccc3C2=O)c2ncccc2c1
 93084                   CCN(CC)c1ccc(/C=C2/C(=O)ON=C2C)cc1
 93085     Cc1cc(=O)oc2cc(OCC(=O)c3ccc4c(c3)NC(=O)CO4)ccc12
 93086             COc1ccc([N+](=O)[O-])cc1NC(=O)c1ccc(C)o1
 Name: smiles, Length: 93087, dtype: object,
 0                      CC(=O)N1CCC2(CC1)NC(=O)N(c1ccccc1)N2
 1                                N#Cc1nnn(-c2ccc(Cl)cc2)c1N
 2             COC(=O)c1ccc(NC(=O)c2ccccc2CC[N+](=O)[O-])cc1
 3                   CCC1NC(=O)c2cccnc2-n2c1nc1ccc(F)cc1c2=O
 4         CC1=CC(=O)/C(=C2/C=C(C(=O)Nc3ccc(S(=O)(=O)Nc4o...
                                 ...
 437924                        CC1CCC2C(C1)OS(=O)(=O)NC2(C)C
 437925                               O=Cc1cc(CCC(=O)O)ccc1O
 437926          O=c1nc(CN2CCN(c3ccc(F)cc3)CC2)[nH]c2ccccc12
 437927               Cc1ccc(C(C)C)c(OCC(O)CN(C)Cc2ccccc2)c1
 437928     CCN(CC(=O)Nc1ccc(C)c(S(=O)(=O)N(C)C)c1)Cc1ccccc1
 Name: smiles, Length: 437929, dtype: object]

In [0]:
result = pd.concat([HIVdata['smiles'], BACEdata['mol'], MUVdata['smiles'], PCBAdata['smiles']])

In [0]:
result

0         CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...
1         C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...
2                          CC(=O)N1c2ccccc2Sc2c1ccc1ccccc21
3           Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1
4                                    O=S(=O)(O)CCS(=O)(=O)O
                                ...
437924                        CC1CCC2C(C1)OS(=O)(=O)NC2(C)C
437925                               O=Cc1cc(CCC(=O)O)ccc1O
437926          O=c1nc(CN2CCN(c3ccc(F)cc3)CC2)[nH]c2ccccc12
437927               Cc1ccc(C(C)C)c(OCC(O)CN(C)Cc2ccccc2)c1
437928     CCN(CC(=O)Nc1ccc(C)c(S(=O)(=O)N(C)C)c1)Cc1ccccc1
Length: 573656, dtype: object

In [0]:
print(len(result))

573656

In [0]:
df = pd.DataFrame(result)

In [0]:
df.to_csv('integratedata.csv')

In [0]:
iD_R = pd.read_csv("integratedata.csv")

In [0]:
iD_R

        Unnamed: 0                                                  0
0                0  CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...
1                1  C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...
2                2                   CC(=O)N1c2ccccc2Sc2c1ccc1ccccc21
3                3    Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1
4                4                             O=S(=O)(O)CCS(=O)(=O)O
...            ...                                                ...
573651      437924                      CC1CCC2C(C1)OS(=O)(=O)NC2(C)C
573652      437925                             O=Cc1cc(CCC(=O)O)ccc1O
573653      437926        O=c1nc(CN2CCN(c3ccc(F)cc3)CC2)[nH]c2ccccc12
573654      437927             Cc1ccc(C(C)C)c(OCC(O)CN(C)Cc2ccccc2)c1
573655      437928   CCN(CC(=O)Nc1ccc(C)c(S(=O)(=O)N(C)C)c1)Cc1ccccc1

[573656 rows x 2 columns]

----------------------
zinc ch
----------------------

In [0]:
zinc = open("ZINC-downloader-2D-smi.uri",'w')

In [0]:
print(zinc)

<_io.TextIOWrapper name='ZINC-downloader-2D-smi.uri' mode='w' encoding='UTF-8'>

In [0]:
ls

bace.csv  integratedata.csv  Mydata.curl  usual.sdf.csh
HIV.csv   muv.csv            pcba.csv     ZINC-downloader-2D-smi.uri

In [0]:
import os

In [0]:
os.system("csh Mydata.curl")

32512

In [0]:
import mkdir
import wget

In [0]:
from ftplib import FTP

In [8]:
pip install urllib3

Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/dist-packages (1.24.3)

In [0]:
import urllib

In [0]:
data = urllib.request.urlretrieve("ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_26.sdf.gz")

In [12]:
cd /content/drive/My\ Drive/Data.csv

/content/drive/My Drive/Data.csv

In [13]:
ls

 BACE.zip                                HIV.zip
 Brain-Tumor-Segmentation-3D-UNet-CNN/   LSTM_Chem-master/
 CHEMBLDATASET                           MVU.zip
'Colab Notebooks'/                       PCBA.zip
 Data.csv/                               youtube/
 deep_learning_coronavirus_cure/

In [9]:
pip install filetype

Collecting filetype
  Downloading https://files.pythonhosted.org/packages/1c/78/047cf0f371f8faafab05b5062f902d4bedd945d436544b30db692622ab84/filetype-1.0.5-py2.py3-none-any.whl
Installing collected packages: filetype
Successfully installed filetype-1.0.5

In [0]:
import filetype

In [0]:
b = filetype.guess("CHEMBLDATASET")

In [17]:
print(b)

<filetype.types.archive.Gz object at 0x7f6e70d6e908>

In [0]:
a = filetype.guess("BACE.zip")

In [0]:
print(a)

<filetype.types.archive.Zip object at 0x7fd1a09f8400>

In [0]:
import gzip

In [0]:
input = gzip.GzipFile("CHEMBLDATASET", 'rb')
s = input.read()
input.close()

In [6]:
output = open("/content/drive/My Drive/CHEMBLDATASET", 'wb')
output.write(s)
output.close()

print("done")

done

In [0]:
chdcon = filetype.guess("CHEMBLDATASET.sdf")

In [16]:
print(chdcon)

None

In [0]:
my_file = 'CHEMBLDATASET'
base = os.path.splitext(my_file)[0]
os.rename(my_file, base + '.sdf')